// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserMessage struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (m *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(m, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserMessage) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *UserMessage) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	UserMessage          *UserMessage `protobuf:"bytes,1,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUserMessage() *UserMessage {
	if m != nil {
		return m.UserMessage
	}
	return nil
}

type ListUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

type ListUserResponse struct {
	UserMessages         []*UserMessage `protobuf:"bytes,1,rep,name=user_messages,json=userMessages,proto3" json:"user_messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUserResponse) Reset()         { *m = ListUserResponse{} }
func (m *ListUserResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserResponse) ProtoMessage()    {}
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *ListUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponse.Unmarshal(m, b)
}
func (m *ListUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponse.Marshal(b, m, deterministic)
}
func (m *ListUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponse.Merge(m, src)
}
func (m *ListUserResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserResponse.Size(m)
}
func (m *ListUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponse proto.InternalMessageInfo

func (m *ListUserResponse) GetUserMessages() []*UserMessage {
	if m != nil {
		return m.UserMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*UserMessage)(nil), "user.user.UserMessage")
	proto.RegisterType((*GetUserRequest)(nil), "user.user.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "user.user.GetUserResponse")
	proto.RegisterType((*ListUserRequest)(nil), "user.user.ListUserRequest")
	proto.RegisterType((*ListUserResponse)(nil), "user.user.ListUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4f, 0x4f, 0xbb, 0x40,
	0x10, 0x0d, 0xbf, 0xf6, 0xd7, 0x86, 0x01, 0x6d, 0xdd, 0x83, 0x22, 0x5e, 0x90, 0x53, 0xbd, 0xd0,
	0xa4, 0x1e, 0x4c, 0xe3, 0xc5, 0x18, 0xe3, 0x9f, 0xa4, 0xd6, 0x84, 0xc6, 0x8b, 0x17, 0x42, 0xe9,
	0x04, 0xb1, 0x85, 0xc5, 0xdd, 0x45, 0xbf, 0x85, 0x9f, 0xd9, 0xec, 0x16, 0xe9, 0x6a, 0xaa, 0x17,
	0x98, 0x79, 0x6f, 0x66, 0xde, 0x7b, 0xc9, 0x02, 0x54, 0x1c, 0x59, 0x50, 0x32, 0x2a, 0x28, 0x31,
	0x55, 0x2d, 0x3f, 0x3e, 0x05, 0xeb, 0x91, 0x23, 0xbb, 0x47, 0xce, 0xe3, 0x14, 0xc9, 0x01, 0x74,
	0x25, 0x1c, 0x65, 0x0b, 0xc7, 0xf0, 0x8c, 0x81, 0x19, 0x76, 0x64, 0x7b, 0xb7, 0x20, 0x04, 0xda,
	0x45, 0x9c, 0xa3, 0xf3, 0x4f, 0xa1, 0xaa, 0x26, 0xc7, 0x60, 0x97, 0xcf, 0xb4, 0xc0, 0xa8, 0xa8,
	0xf2, 0x39, 0x32, 0xa7, 0xa5, 0x38, 0x4b, 0x61, 0x53, 0x05, 0x91, 0x3e, 0xb4, 0xe2, 0x14, 0x9d,
	0xb6, 0x67, 0x0c, 0xfe, 0x87, 0xb2, 0xf4, 0x4f, 0x60, 0xf7, 0x06, 0x85, 0xd4, 0x0c, 0xf1, 0xb5,
	0x42, 0x2e, 0x7e, 0xd5, 0xf4, 0x27, 0xd0, 0x6b, 0x46, 0x79, 0x49, 0x0b, 0x8e, 0x64, 0x0c, 0xb6,
	0x9a, 0xcd, 0xd7, 0x7e, 0xd5, 0x82, 0x35, 0xda, 0x0f, 0x9a, 0x40, 0x81, 0x96, 0x26, 0xb4, 0xaa,
	0x4d, 0xe3, 0xef, 0x41, 0x6f, 0x92, 0x71, 0x5d, 0xd9, 0x7f, 0x80, 0xfe, 0x06, 0xaa, 0x15, 0xce,
	0x61, 0x47, 0x57, 0xe0, 0x8e, 0xe1, 0xb5, 0xfe, 0x90, 0xb0, 0x35, 0x09, 0x3e, 0xfa, 0x30, 0xa0,
	0x2d, 0x59, 0x72, 0x01, 0xdd, 0xda, 0x3a, 0x39, 0xd4, 0x36, 0xbf, 0x27, 0x77, 0xdd, 0x6d, 0x54,
	0xed, 0xe3, 0x0a, 0xcc, 0x2f, 0x6f, 0x9c, 0xe8, 0x83, 0x3f, 0x42, 0xb8, 0x47, 0x5b, 0xb9, 0xf5,
	0x95, 0xcb, 0xf1, 0xd3, 0xd9, 0x2d, 0xcd, 0x71, 0x78, 0x5d, 0xad, 0x56, 0xd1, 0x4c, 0xc4, 0xc9,
	0x32, 0x9a, 0x21, 0x7b, 0xcb, 0x12, 0x8c, 0xa6, 0x28, 0xde, 0x29, 0x5b, 0x66, 0x45, 0x3a, 0x2c,
	0x19, 0x7d, 0xc1, 0x44, 0x34, 0x7f, 0x79, 0x6b, 0xde, 0x51, 0x6f, 0xe5, 0xf4, 0x33, 0x00, 0x00,
	0xff, 0xff, 0x38, 0x43, 0xe5, 0x5f, 0x39, 0x02, 0x00, 0x00,
}
